### PR TITLE
Fix example app build error

### PR DESCRIPTION
**Pull request by hewigovens**
also fixed some warnings

### CODE REVIEW

**Review by llbartekll — APPROVED** [review]

**Review by llbartekll — CHANGES_REQUESTED** [review]
thank you @hewigovens for your contribution, will merge your PR but current build fails.

**Comment by hewigovens** [comment]
I have 6 tests failed locally, weird

**Comment by llbartekll** [comment]
> I have 6 tests failed locally, weird
hmm in WCTests or IntegrationTests target?

**Comment by hewigovens** [comment]
Integration tests

**Comment by llbartekll** [comment]
so it is probably too short expectation timeout relative to your networking conditions. it is going to be increased.

**Review by llbartekll — APPROVED** [review]

**Comment by hewigovens** [comment]
Another suggestion: also build example app in CI

**Pull request merged**
