### PR TITLE
Make session proposals `Topic` as public

### LINKED ISSUE #148: Refactor internal objects to manage only needed data
In delegated method `func didReceive(sessionProposal: SessionProposal)` uts not able to retrieve topic to determine the connection

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #148

### CODE REVIEW

**Review by MisterVants — APPROVED** [review]

**Review by llbartekll — APPROVED** [review]

**Comment by llbartekll** [comment]
Hey @vladyslav-iosdev, thanks for your PR, could you share with us what is the use case why you need the topic of proposal to be public?

**Comment by vladyslav-iosdev** [comment]
Hi guys, thx a lot for approving the PR.
for case when we want to keep proposal servers information we only are able to retrieve it in `func didReceive(sessionProposal: SessionProposal)` method. Also we want to keep URI that we wwas trying to connect with `client.pair(uri: <uri>)`. that is why we need to match if initial paired uri, has the same `Topic`, For identifying whitch call of `client.pair(uri: <uri>)` related to `func didReceive(sessionProposal: SessionProposal)`

**Comment by llbartekll** [comment]
topic that you have in `pairing uri` is different from that `session proposal topic` so you are not able to link pairing and session this way. Could you explain why you want to know their relation? I think the session should have all you need.
Also keep in mind that topic in session proposal will be different from the one you receive in `didSettle(session: Session`

**Comment by vladyslav-iosdev** [comment]
so in case if the `.topic` is different for these two methods `func didReceive(sessionProposal: SessionProposal)` `func didSettle(session: Session)` then yes, that makes no sence. but if it is the same, then with the `topic` we can identify connecting session and be able to store it. isn't it?

**Comment by vladyslav-iosdev** [comment]
just to notice. we was using timeout timers for V1 connections, so for each url we trying to connect, we created a new timer, and removed it once received `func server(_ server: Server, shouldStart session: Session, completion: @escaping (Session.WalletInfo) -> Void)` and there we were able to match these connection urls and remove needed timer. i was hoping that it could work the same for v2.

**Comment by llbartekll** [comment]
Actually they cannot be the same because session payloads and session proposal are transported on different encrypted channels. We are still considering client's public interface and it is possible that in beta version you will receive session in approve completion but for now I think that topics that you receive in `didSettle(session: Session)` are the only you should keep track of.

**Comment by vladyslav-iosdev** [comment]
ok, i see, thx a lot for the explanation

**Comment by vladyslav-iosdev** [comment]
One more question: how we can determine what servers are supported for session in `func didSettle(session: Session)`?

**Comment by llbartekll** [comment]
You are providing a relayUrl in init params

**Comment by vladyslav-iosdev** [comment]
sorry my failt, i meant chainIds or (sessionProposal.permissions.blockchains). here is an example: 
1. we are trying to connect with: `try client.pair(uri: <uri>)`
2. after some time we are getting called delegated method `func didReceive(sessionProposal: SessionProposal)` here we are able to get `chainIds`, `methods` and other needed information.
3. after approving `sessionProposal` we get called delegated method `func didSettle(session: Session)`

So the pboblem here is that the valid topic we got only in `func didSettle(session: Session)`, and there is no way take chainids from step 2, and use it in step 3. 
storing chainIds somewhere without right idenitifier doesnt help us as it could be rewritten by another call from step 1

**Comment by llbartekll** [comment]
OK I see, this is an issue, the Session object you get in step 3 should contain permissions.

**Pull request merged**
